Add rwd for history
mad-rat/cconverter pull request #70
Opened 2020-08-18 21:00 UTC by MateuszWasik

2020-08-19 09:58 UTC, skrzepij requested changes

2020-08-19 09:58 UTC, skrzepij commented on src/components/ExchangeRateHistoryComponent/ExchangeRateHistoryComponent.scss
> +      font-size: 11px;
please use rem unit thanks a lot bro bro brooooo

2020-08-28 19:30 UTC, MateuszWasik commented on src/components/ExchangeRateHistoryComponent/ExchangeRateHistoryComponent.scss
> +      font-size: 11px;
Done

2020-08-28 19:33 UTC, skrzepij approved these changes

2020-08-28 19:33 UTC, skrzepij commented on src/components/ChartComponent/ChartComponent.scss
> +    height: 430px
I think this one is overdone. try to remove it ;) 

`.line-chart` as a child of this container, should expand `.chart-container` height automatically :)

2020-08-28 19:33 UTC, skrzepij commented on src/components/ExchangeRateHistoryComponent/ExchangeRateHistoryComponent.scss
> +      height: 30px;
if this style is set in media query above, then shouldn't be needed here :P

2020-08-28 19:34 UTC, merged