Add eslint, prettier and vscode configs and some missing interfaces
mad-rat/cconverter pull request #80
Opened 2021-01-18 08:20 UTC by skrzepij

2021-01-18 14:16 UTC, MateuszWasik requested changes
Please fix build

2021-01-18 14:17 UTC, MateuszWasik commented
🤷‍♂️

2021-01-19 18:23 UTC, MateuszWasik approved these changes

2021-01-19 18:23 UTC, skrzepij reviewed
changes fixing build

2021-01-20 08:49 UTC, merged